### ISSUE TITLE
推理报错

### ISSUE THREAD

**Issue by lswc225** [foxyear-kyumin/lip_mask#1]
感谢您的工作,我在推理的时候遇到这个问题,环境按照文档搭建的.

大概该如何修复呢:
Traceback (most recent call last):
  File "/root/lip_mask/inference.py", line 35, in <module>
    fa = face_alignment.FaceAlignment(face_alignment.LandmarksType.TWO_D, flip_input=False, device='cuda')
  File "/root/miniconda3/envs/lipmask/lib/python3.9/site-packages/face_alignment/api.py", line 80, in __init__
    self.face_detector = face_detector_module.FaceDetector(device=device, verbose=verbose, **face_detector_kwargs)
  File "/root/miniconda3/envs/lipmask/lib/python3.9/site-packages/face_alignment/detection/sfd/sfd_detector.py", line 24, in __init__
    model_weights = load_url(models_urls['s3fd'])
  File "/root/miniconda3/envs/lipmask/lib/python3.9/site-packages/torch/hub.py", line 750, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "/root/miniconda3/envs/lipmask/lib/python3.9/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/root/miniconda3/envs/lipmask/lib/python3.9/site-packages/torch/serialization.py", line 1051, in _legacy_load
    typed_storage._untyped_storage._set_from_file(
RuntimeError: unexpected EOF, expected 1202694 more bytes. The file might be corrupted.

**Comment by yaleimeng** [comment]
看起来似乎是s3fd的权重下载有问题，文件不完整。下载放到指定目录就行

**Comment by lswc225** [comment]
> 看起来似乎是s3fd的权重下载异常，文件不完整。手动下载放到指定目录~/.cache/torch/hub/checkpoints就行 参考链接： https://www.adrianbulat.com/downloads/python-fan/s3fd-619a316812.pth http://8.141.166.38/s3fd-619a316812.pth?preview

感谢回复,按照你的方式已解决
